import React from "react";

import "../styles/main.css";

import { Montserrat, OpenSans } from "@/lib/font";

import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${Montserrat.variable} ${OpenSans.variable} font-opensans`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
