import React from "react";

import "../styles/main.css";

import { Montserrat, OpenSans } from "@/lib/font";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

// include all compulsory metadata
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // image: "/images/og-image.png",
  url: "https://teknico.dev",
  // twitter: "@vercel",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${Montserrat.variable} ${OpenSans.variable} font-opensans`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
